#!/bin/bash

./compute-wer --text --mode=present ark:/dev/fd/5 ark:/dev/fd/6 \
  5< <(cat /dev/stdin | \
    awk '{print NR" "$0}') \
  6< <(cat ~/wsj1/dev93.txt | sed 's/<NOISE>//g' | \
    awk '{print NR" "$0}')
