#!/usr/bin/bash

testspk="p302 p254 p228 p340 p306 p280 p360 p248 p351 p276"
for dir in /home/speech/vctk/wav16/*/; do
  dname="$(echo $dir | rev | cut -d/ -f2 | rev)"
  istest=false
  for spk in $testspk; do
    if [ "$spk" == "$dname" ]; then istest=true; break; fi
  done

  # testspk can be used as testcase later
  if $istest; then continue; fi
  for wav in $dir/test/*.wav; do
    readlink -f $wav | awk '{print "'$dname' "$0}' 1>&2
  done
  for wav in $dir/*.wav; do
    readlink -f $wav | awk '{print "'$dname' "$0}'
  done
done > .train.list 2> test.list

cat .train.list | awk '{print $1}' | sort | uniq > vocab
shuf .train.list > train.list
