#!/usr/bin/bash

cat ~/vctk/speaker-info.txt  | awk 'NR>1{print $1}' \
  | shuf | awk 'NR<=10{print "test "$1} NR>10{print "train "$1}' > .list
cat .list | grep test | awk '{print $2}' > spk_test.list
cat .list | grep train | awk '{print $2}' > spk_train.list
rm .list
